apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  project: rmf-web-example-full

bases:
  - ../../base/keycloak

images:
  - name: quay.io/keycloak/keycloak
    newName: rmf-web/keycloak
    newTag: '12.04'
