packages:
  - 'packages/*'
  - 'pipenv-install'

allowBuilds:
  '@nestjs/core': true
  '@openapitools/openapi-generator-cli': true
  '@swc/core': true
  edgedriver: true
  esbuild: true
  geckodriver: true

minimumReleaseAgeExclude:
  - '@puppeteer/browsers@3.2.1'

# These overrides were produced mostly during https://github.com/open-rmf/rmf-web/pull/1083 when
# resolving security vulnerabilities. This is considered technical debt and should be progressively
# resolved by updating the dependencies to versions that use fixed versions of further upstream
# dependencies.
overrides:
  "@grpc/grpc-js": ^1.14.4
  ws: ^8.21.3
  deepmerge-ts: ^8.0.1
  serialize-javascript: ^7.0.5
  uuid: ^11.1.1
  esbuild: ^0.28.2
  undici: ^7.29.0
  "@puppeteer/browsers": ^3.2.1
