########################################################
#                                                      #
# this file is generated by ros_tortoise, do not edit! #
#                                                      #
########################################################

from tortoise import fields


class AffineImageMixin:
    name = fields.TextField()
    x_offset = fields.FloatField()
    y_offset = fields.FloatField()
    yaw = fields.FloatField()
    scale = fields.FloatField()
    encoding = fields.TextField()
    data = fields.BinaryField()


class BuildingMapMixin:
    name = fields.TextField()
    levels = fields.JSONField()
    lifts = fields.JSONField()


class DoorMixin:
    name = fields.TextField()
    v1_x = fields.FloatField()
    v1_y = fields.FloatField()
    v2_x = fields.FloatField()
    v2_y = fields.FloatField()
    door_type = fields.SmallIntField()
    motion_range = fields.FloatField()
    motion_direction = fields.IntField()


class GraphMixin:
    name = fields.TextField()
    vertices = fields.JSONField()
    edges = fields.JSONField()
    params = fields.JSONField()


class GraphEdgeMixin:
    v1_idx = fields.IntField()
    v2_idx = fields.IntField()
    params = fields.JSONField()
    edge_type = fields.SmallIntField()


class GraphNodeMixin:
    x = fields.FloatField()
    y = fields.FloatField()
    name = fields.TextField()
    params = fields.JSONField()


class LevelMixin:
    name = fields.TextField()
    elevation = fields.FloatField()
    images = fields.JSONField()
    places = fields.JSONField()
    doors = fields.JSONField()
    nav_graphs = fields.JSONField()
    wall_graph = fields.JSONField()


class LiftMixin:
    name = fields.TextField()
    levels = fields.JSONField()
    doors = fields.JSONField()
    wall_graph = fields.JSONField()
    ref_x = fields.FloatField()
    ref_y = fields.FloatField()
    ref_yaw = fields.FloatField()
    width = fields.FloatField()
    depth = fields.FloatField()


class ParamMixin:
    name = fields.TextField()
    type = fields.IntField()
    value_int = fields.IntField()
    value_float = fields.FloatField()
    value_string = fields.TextField()
    value_bool = fields.BooleanField()


class PlaceMixin:
    name = fields.TextField()
    x = fields.FloatField()
    y = fields.FloatField()
    yaw = fields.FloatField()
    position_tolerance = fields.FloatField()
    yaw_tolerance = fields.FloatField()


class GetBuildingMap_RequestMixin:
    pass


class GetBuildingMap_ResponseMixin:
    building_map = fields.JSONField()
