########################################################
#                                                      #
# this file is generated by ros_tortoise, do not edit! #
#                                                      #
########################################################

from tortoise import fields


class LiftRequestMixin:
    lift_name = fields.TextField()
    request_time = fields.DatetimeField()
    session_id = fields.TextField()
    request_type = fields.SmallIntField()
    destination_floor = fields.TextField()
    door_state = fields.SmallIntField()


class LiftStateMixin:
    lift_time = fields.DatetimeField()
    lift_name = fields.TextField()
    available_floors = fields.JSONField()
    current_floor = fields.TextField()
    destination_floor = fields.TextField()
    door_state = fields.SmallIntField()
    motion_state = fields.SmallIntField()
    available_modes = fields.BinaryField()
    current_mode = fields.SmallIntField()
    session_id = fields.TextField()
