########################################################
#                                                      #
# this file is generated by ros_tortoise, do not edit! #
#                                                      #
########################################################

from tortoise import fields


class DestinationRequestMixin:
    fleet_name = fields.TextField()
    robot_name = fields.TextField()
    destination = fields.JSONField()
    task_id = fields.TextField()


class DockMixin:
    fleet_name = fields.TextField()
    params = fields.JSONField()


class DockParameterMixin:
    start = fields.TextField()
    finish = fields.TextField()
    path = fields.JSONField()


class DockSummaryMixin:
    docks = fields.JSONField()


class FleetStateMixin:
    name = fields.TextField()
    robots = fields.JSONField()


class LocationMixin:
    t = fields.DatetimeField()
    x = fields.FloatField()
    y = fields.FloatField()
    yaw = fields.FloatField()
    level_name = fields.TextField()
    index = fields.BigIntField()


class ModeParameterMixin:
    name = fields.TextField()
    value = fields.TextField()


class ModeRequestMixin:
    fleet_name = fields.TextField()
    robot_name = fields.TextField()
    mode = fields.JSONField()
    task_id = fields.TextField()
    parameters = fields.JSONField()


class PathRequestMixin:
    fleet_name = fields.TextField()
    robot_name = fields.TextField()
    path = fields.JSONField()
    task_id = fields.TextField()


class PauseRequestMixin:
    fleet_name = fields.TextField()
    robot_name = fields.TextField()
    mode_request_id = fields.BigIntField()
    type = fields.IntField()
    at_checkpoint = fields.IntField()


class RobotModeMixin:
    mode = fields.IntField()
    mode_request_id = fields.BigIntField()


class RobotStateMixin:
    name = fields.TextField()
    model = fields.TextField()
    task_id = fields.TextField()
    seq = fields.BigIntField()
    mode = fields.JSONField()
    battery_percent = fields.FloatField()
    location = fields.JSONField()
    path = fields.JSONField()
