########################################################
#                                                      #
# this file is generated by ros_tortoise, do not edit! #
#                                                      #
########################################################

from tortoise import fields


class AssetMixin:
    guid = fields.TextField()
    type = fields.TextField()


class TraitMixin:
    key = fields.TextField()
    value = fields.JSONField()


class WorkcellConfigurationMixin:
    time = fields.DatetimeField()
    guid = fields.TextField()
    type = fields.TextField()
    assets = fields.JSONField()
    traits = fields.JSONField()


class WorkcellRequestMixin:
    time = fields.DatetimeField()
    request_guid = fields.TextField()
    target_guid = fields.TextField()


class WorkcellResultMixin:
    time = fields.DatetimeField()
    request_guid = fields.TextField()
    source_guid = fields.TextField()
    status = fields.SmallIntField()


class WorkcellStateMixin:
    time = fields.DatetimeField()
    guid = fields.TextField()
    mode = fields.IntField()
    request_guid_queue = fields.JSONField()
