########################################################
#                                                      #
# this file is generated by ros_tortoise, do not edit! #
#                                                      #
########################################################

from tortoise import fields


class BehaviorMixin:
    name = fields.TextField()
    parameters = fields.JSONField()


class BehaviorParameterMixin:
    name = fields.TextField()
    value = fields.TextField()


class BidNoticeMixin:
    task_profile = fields.JSONField()
    time_window = fields.JSONField()


class BidProposalMixin:
    fleet_name = fields.TextField()
    task_profile = fields.JSONField()
    prev_cost = fields.FloatField()
    new_cost = fields.FloatField()
    finish_time = fields.DatetimeField()
    robot_name = fields.TextField()


class CleanMixin:
    start_waypoint = fields.TextField()


class DeliveryMixin:
    task_id = fields.TextField()
    items = fields.JSONField()
    pickup_place_name = fields.TextField()
    pickup_dispenser = fields.TextField()
    pickup_behavior = fields.JSONField()
    dropoff_place_name = fields.TextField()
    dropoff_ingestor = fields.TextField()
    dropoff_behavior = fields.JSONField()


class DispatchRequestMixin:
    fleet_name = fields.TextField()
    task_profile = fields.JSONField()
    method = fields.SmallIntField()


class LoopMixin:
    task_id = fields.TextField()
    robot_type = fields.TextField()
    num_loops = fields.IntField()
    start_name = fields.TextField()
    finish_name = fields.TextField()


class StationMixin:
    task_id = fields.TextField()
    robot_type = fields.TextField()
    place_name = fields.TextField()


class TaskDescriptionMixin:
    start_time = fields.DatetimeField()
    task_type = fields.JSONField()
    station = fields.JSONField()
    loop = fields.JSONField()
    delivery = fields.JSONField()
    clean = fields.JSONField()


class TaskProfileMixin:
    task_id = fields.TextField()
    submission_time = fields.DatetimeField()
    description = fields.JSONField()


class TaskSummaryMixin:
    fleet_name = fields.TextField()
    task_id = fields.TextField()
    task_profile = fields.JSONField()
    state = fields.IntField()
    status = fields.TextField()
    submission_time = fields.DatetimeField()
    start_time = fields.DatetimeField()
    end_time = fields.DatetimeField()
    robot_name = fields.TextField()


class TaskTypeMixin:
    type = fields.IntField()


class TasksMixin:
    tasks = fields.JSONField()


class TowMixin:
    task_id = fields.TextField()
    object_type = fields.TextField()
    is_object_id_known = fields.BooleanField()
    object_id = fields.TextField()
    pickup_place_name = fields.TextField()
    is_dropoff_place_known = fields.BooleanField()
    dropoff_place_name = fields.TextField()


class CancelTask_RequestMixin:
    requester = fields.TextField()
    task_id = fields.TextField()


class CancelTask_ResponseMixin:
    success = fields.BooleanField()


class GetTaskList_RequestMixin:
    requester = fields.TextField()
    task_id = fields.JSONField()


class GetTaskList_ResponseMixin:
    success = fields.BooleanField()
    active_tasks = fields.JSONField()
    terminated_tasks = fields.JSONField()


class SubmitTask_RequestMixin:
    requester = fields.TextField()
    start_time = fields.DatetimeField()
    description = fields.JSONField()
    evaluator = fields.SmallIntField()


class SubmitTask_ResponseMixin:
    success = fields.BooleanField()
    task_id = fields.TextField()
