########################################################
#                                                      #
# this file is generated by ros_tortoise, do not edit! #
#                                                      #
########################################################

from tortoise import fields
from ._ros_time import RosTimeField


class AssetMixin():
    guid = fields.TextField()
    type = fields.TextField()

class TraitMixin():
    key = fields.TextField()
    value = fields.JSONField()

class WorkcellConfigurationMixin():
    time = RosTimeField()
    guid = fields.TextField()
    type = fields.TextField()
    assets = fields.JSONField()
    traits = fields.JSONField()

class WorkcellRequestMixin():
    time = RosTimeField()
    request_guid = fields.TextField()
    target_guid = fields.TextField()

class WorkcellResultMixin():
    time = RosTimeField()
    request_guid = fields.TextField()
    source_guid = fields.TextField()
    status = fields.SmallIntField()

class WorkcellStateMixin():
    time = RosTimeField()
    guid = fields.TextField()
    mode = fields.IntField()
    request_guid_queue = fields.JSONField()

