########################################################
#                                                      #
# this file is generated by ros_tortoise, do not edit! #
#                                                      #
########################################################

from tortoise import fields
from .fields import RosTimeField


class DoorModeMixin():
    value = fields.IntField()

class DoorRequestMixin():
    request_time = RosTimeField()
    requester_id = fields.TextField()
    door_name = fields.TextField()
    requested_mode = fields.JSONField()

class DoorSessionsMixin():
    door_name = fields.TextField()
    sessions = fields.JSONField()

class DoorStateMixin():
    door_time = RosTimeField()
    door_name = fields.TextField()
    current_mode = fields.JSONField()

class SessionMixin():
    request_time = RosTimeField()
    requester_id = fields.TextField()

class SupervisorHeartbeatMixin():
    all_sessions = fields.JSONField()

