apiVersion: batch/v1
kind: Job
metadata:
  name: reporting-server-migrations-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: reporting-server-migrations
          image: rmf-web/reporting-server-migrations
          imagePullPolicy: Never # remove this in a real deployment
          env:
            - name: RMF_REPORT_REST_SERVER_CONFIG
              value: /reporting-server-config/reporting_server_config.py
          
          volumeMounts:
            - mountPath: /jwt-configmap
              name: jwt-pub-key
            - mountPath: /reporting-server-config
              name: reporting-server-config
      volumes:
        - name: jwt-pub-key
          configMap:
            name: jwt-pub-key
        - name: reporting-server-config
          configMap:
            name: reporting-server-config