apiVersion: v1
kind: Service
metadata:
  name: rmf-server
  labels:
    app: rmf-server
spec:
  type: LoadBalancer
  selector:
    app: rmf-server
  ports:
    - protocol: TCP
      port: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmf-server
  labels:
    app: rmf-server
spec:
  selector:
    matchLabels:
      app: rmf-server
  template:
    metadata:
      labels:
        app: rmf-server
    spec:
      containers:
      - name: rmf-server
        image: rmf-web/rmf-server
        imagePullPolicy: Never # remove this in a real deployment
        ports:
          - containerPort: 8000
        env:
          - name: RMF_API_SERVER_CONFIG
            value: /rmf-server-config/rmf_server_config.py
        volumeMounts:
          - mountPath: /jwt-configmap
            name: jwt-pub-key
          - mountPath: /rmf-server-config
            name: rmf-server-config
      volumes:
        - name: jwt-pub-key
          configMap:
            name: jwt-pub-key
        - name: rmf-server-config
          configMap:
            name: rmf-server-config
      hostNetwork: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rmf-server
  labels:
    app: rmf-server
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
    - hosts:
      - example.com
  rules:
    - host: example.com
      http:
        paths:
          - path: /rmf/api/v1(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: rmf-server
                port:
                  number: 8000
