# generated by datamodel-codegen:
#   filename:  cancel_task_response.schema.json

from __future__ import annotations

from pydantic import BaseModel, Field

from ..simple_response import schema


class TaskCancelResponse(BaseModel):
    __root__: schema.SimpleResponse = Field(
        ...,
        description="Response to a request to cancel a task",
        title="Task Cancel Response",
    )
