# generated by datamodel-codegen:
#   filename:  cancel_task_response.json

from __future__ import annotations

from pydantic import Field, RootModel

from . import simple_response


class TaskCancelResponse(RootModel[simple_response.SimpleResponse]):
    root: simple_response.SimpleResponse = Field(
        ...,
        description="Response to a request to cancel a task",
        title="Task Cancel Response",
    )
