# generated by datamodel-codegen:
#   filename:  cancel_task_response.json

from __future__ import annotations

from pydantic import BaseModel, Field

from . import simple_response


class TaskCancelResponse(BaseModel):
    __root__: simple_response.SimpleResponse = Field(
        ...,
        description="Response to a request to cancel a task",
        title="Task Cancel Response",
    )
