# generated by datamodel-codegen:
#   filename:  dispatch_task_request.json

from __future__ import annotations

from pydantic import BaseModel, Field
from typing_extensions import Literal

from . import task_request


class DispatchTaskRequest(BaseModel):
    type: Literal["dispatch_task_request"] = Field(
        ..., description="Indicate that this is a task dispatch request"
    )
    request: task_request.TaskRequest
