# generated by datamodel-codegen:
#   filename:  dispatch_task_request.json

from __future__ import annotations

from pydantic import BaseModel, Field

from . import task_request


class DispatchTaskRequest(BaseModel):
    type: str = Field(..., description="Indicate that this is a task dispatch request")
    request: task_request.TaskRequest
