# generated by datamodel-codegen:
#   filename:  dispatch_task_response.json

from __future__ import annotations

from typing import List, Optional, Union

from pydantic import BaseModel, Field, RootModel
from typing_extensions import Literal

from . import error, task_state


class TaskDispatchResponse2(BaseModel):
    success: Optional[Literal[False]] = None
    errors: Optional[List[error.Error]] = Field(
        default=None, description="Any error messages explaining why the request failed"
    )


class TaskDispatchResponse1(BaseModel):
    success: Literal[True]
    state: task_state.TaskState


class TaskDispatchResponse(
    RootModel[Union[TaskDispatchResponse1, TaskDispatchResponse2]]
):
    root: Union[TaskDispatchResponse1, TaskDispatchResponse2] = Field(
        ...,
        description="Response to a task dispatch request",
        title="Task Dispatch Response",
    )
