# generated by datamodel-codegen:
#   filename:  error.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field, conint


class Error(BaseModel):
    code: Optional[conint(ge=0)] = Field(
        None, description="A standard code for the kind of error that has occurred"
    )
    category: Optional[str] = Field(None, description="The category of the error")
    detail: Optional[str] = Field(None, description="Details about the error")
