# generated by datamodel-codegen:
#   filename:  fleet_log_update.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field

from . import fleet_log


class TaskEventLogUpdate(BaseModel):
    type: Optional[str] = Field(
        None, description="Indicate that this is a fleet log update"
    )
    data: Optional[fleet_log.FleetState] = None
