# generated by datamodel-codegen:
#   filename:  fleet_log_response.json

from __future__ import annotations

from typing import List, Union

from pydantic import BaseModel, Field

from . import error, fleet_log


class Failure(BaseModel):
    __root__: bool = Field(..., description="The request failed")


class Success(BaseModel):
    __root__: bool = Field(..., description="The request was successful")


class FleetLogResponseItem(BaseModel):
    success: Success
    data: fleet_log.FleetState


class FleetLogResponseItem1(BaseModel):
    success: Failure
    errors: List[error.Error] = Field(
        ..., description="Any error messages explaining why the request failed"
    )


class FleetLogResponse(BaseModel):
    __root__: Union[FleetLogResponseItem, FleetLogResponseItem1] = Field(
        ..., description="Responding to a fleet log request", title="Fleet Log Response"
    )
