# generated by datamodel-codegen:
#   filename:  fleet_log_response.schema.json

from __future__ import annotations

from typing import List, Union

from pydantic import BaseModel, Field

from ..error import schema as schema_1
from ..fleet_log import schema


class Failure(BaseModel):
    __root__: bool = Field(..., description="The request failed")


class Success(BaseModel):
    __root__: bool = Field(..., description="The request was successful")


class FleetLogResponseItem(BaseModel):
    success: Success
    data: schema.FleetState


class FleetLogResponseItem1(BaseModel):
    success: Failure
    errors: List[schema_1.Error] = Field(
        ..., description="Any error messages explaining why the request failed"
    )


class FleetLogResponse(BaseModel):
    __root__: Union[FleetLogResponseItem, FleetLogResponseItem1] = Field(
        ..., description="Responding to a fleet log request", title="Fleet Log Response"
    )
