# generated by datamodel-codegen:
#   filename:  fleet_log.schema.json

from __future__ import annotations

from typing import Dict, List, Optional

from pydantic import BaseModel, Field

from ..log_entry import schema


class FleetState(BaseModel):
    name: Optional[str] = None
    log: Optional[List[schema.LogEntry]] = Field(
        None, description="Log for the overall fleet"
    )
    robots: Optional[Dict[str, List[schema.LogEntry]]] = Field(
        None,
        description="Dictionary of logs for the individual robots. The keys (property names) are the robot names.",
    )
