# generated by datamodel-codegen:
#   filename:  fleet_log_update.json

from __future__ import annotations

from pydantic import BaseModel, Field
from typing_extensions import Literal

from . import fleet_log


class TaskEventLogUpdate(BaseModel):
    type: Literal["fleet_log_update"] = Field(
        ..., description="Indicate that this is a fleet log update"
    )
    data: fleet_log.FleetLog
