# generated by datamodel-codegen:
#   filename:  fleet_state.schema.json

from __future__ import annotations

from typing import Dict, Optional

from pydantic import BaseModel, Field

from ..robot_state import schema


class FleetState(BaseModel):
    name: Optional[str] = None
    robots: Optional[Dict[str, schema.RobotState]] = Field(
        None,
        description="A dictionary of the states of the robots that belong to this fleet",
    )
