# generated by datamodel-codegen:
#   filename:  fleet_log_request.json

from __future__ import annotations

from pydantic import BaseModel, Field
from typing_extensions import Literal


class FleetLogRequest(BaseModel):
    type: Literal["fleet_log_request"] = Field(
        ..., description="Indicate that this is a fleet log request"
    )
    fleet: str = Field(
        ..., description="Specify the name of the fleet whose log should be fetched"
    )
