# generated by datamodel-codegen:
#   filename:  fleet_state_update.schema.json

from __future__ import annotations

from pydantic import BaseModel, Field

from ..fleet_state import schema


class FleetStateUpdate(BaseModel):
    type: str = Field(..., description="Indicate that this is a fleet state update")
    data: schema.FleetState
