# generated by datamodel-codegen:
#   filename:  fleet_state.json

from __future__ import annotations

from typing import Dict, Optional

from pydantic import BaseModel, Field

from . import robot_state


class FleetState(BaseModel):
    name: Optional[str] = None
    robots: Optional[Dict[str, robot_state.RobotState]] = Field(
        default=None,
        description="A dictionary of the states of the robots that belong to this fleet",
    )
