# generated by datamodel-codegen:
#   filename:  fleet_log.json

from __future__ import annotations

from typing import Dict, List, Optional

from pydantic import BaseModel, Field

from . import log_entry


class FleetLog(BaseModel):
    name: Optional[str] = None
    log: Optional[List[log_entry.LogEntry]] = Field(
        default=None, description="Log for the overall fleet"
    )
    robots: Optional[Dict[str, List[log_entry.LogEntry]]] = Field(
        default=None,
        description="Dictionary of logs for the individual robots. The keys (property names) are the robot names.",
    )
