# generated by datamodel-codegen:
#   filename:  fleet_log_response.json

from __future__ import annotations

from typing import List, Union

from pydantic import BaseModel, Field, RootModel
from typing_extensions import Literal

from . import error, fleet_log


class Success(RootModel[Literal[True]]):
    root: Literal[True] = Field(..., description="The request was successful")


class Failure(RootModel[Literal[False]]):
    root: Literal[False] = Field(..., description="The request failed")


class FleetLogResponse1(BaseModel):
    success: Success
    data: fleet_log.FleetLog


class FleetLogResponse2(BaseModel):
    success: Failure
    errors: List[error.Error] = Field(
        ..., description="Any error messages explaining why the request failed"
    )


class FleetLogResponse(RootModel[Union[FleetLogResponse1, FleetLogResponse2]]):
    root: Union[FleetLogResponse1, FleetLogResponse2] = Field(
        ..., description="Responding to a fleet log request", title="Fleet Log Response"
    )
