# generated by datamodel-codegen:
#   filename:  fleet_log_update.schema.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field

from ..fleet_log import schema


class TaskEventLogUpdate(BaseModel):
    type: Optional[str] = Field(
        None, description="Indicate that this is a fleet log update"
    )
    data: Optional[schema.FleetState] = None
