# generated by datamodel-codegen:
#   filename:  interrupt_task_response.json

from __future__ import annotations

from pydantic import Field, RootModel

from . import token_response


class TaskInterruptionResponse(RootModel[token_response.TokenResponse]):
    root: token_response.TokenResponse = Field(
        ...,
        description="Response to a request for a task to be interrupted",
        title="Task Interruption Response",
    )
