# generated by datamodel-codegen:
#   filename:  kill_task_response.schema.json

from __future__ import annotations

from pydantic import BaseModel, Field

from ..simple_response import schema


class TaskKillResponse(BaseModel):
    __root__: schema.SimpleResponse = Field(
        ...,
        description="Response to a request to kill a task",
        title="Task Kill Response",
    )
