# generated by datamodel-codegen:
#   filename:  kill_task_request.json

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field
from typing_extensions import Literal


class TaskKillRequest(BaseModel):
    type: Literal["kill_task_request"] = Field(
        ..., description="Indicate that this is a task kill request"
    )
    task_id: str = Field(..., description="Specify the task ID to kill")
    labels: Optional[List[str]] = Field(
        default=None, description="Labels to describe the purpose of the kill"
    )
