# generated by datamodel-codegen:
#   filename:  kill_task_request.schema.json

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class TaskKillRequest(BaseModel):
    type: str = Field(..., description="Indicate that this is a task kill request")
    task_id: str = Field(..., description="Specify the task ID to kill")
    labels: Optional[List[str]] = Field(
        None, description="Labels to describe the purpose of the kill"
    )
