# generated by datamodel-codegen:
#   filename:  log_entry.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field, conint


class Tier(Enum):
    uninitialized = "uninitialized"
    info = "info"
    warning = "warning"
    error = "error"


class LogEntry(BaseModel):
    seq: conint(ge=0, lt=4294967296) = Field(
        ...,
        description="Sequence number for this entry. Each entry has a unique sequence number which monotonically increase, until integer overflow causes a wrap around.",
    )
    tier: Tier = Field(..., description="The importance level of the log entry")
    unix_millis_time: int
    text: str = Field(..., description="The text of the log entry")
