# generated by datamodel-codegen:
#   filename:  resume_task_response.schema.json

from __future__ import annotations

from pydantic import BaseModel, Field

from ..simple_response import schema


class TaskResumeResponse(BaseModel):
    __root__: schema.SimpleResponse = Field(
        ...,
        description="Response to a request to resume a task",
        title="Task Resume Response",
    )
