# generated by datamodel-codegen:
#   filename:  resume_task_response.json

from __future__ import annotations

from pydantic import Field, RootModel

from . import simple_response


class TaskResumeResponse(RootModel[simple_response.SimpleResponse]):
    root: simple_response.SimpleResponse = Field(
        ...,
        description="Response to a request to resume a task",
        title="Task Resume Response",
    )
