# generated by datamodel-codegen:
#   filename:  resume_task_response.json

from __future__ import annotations

from pydantic import BaseModel, Field

from . import simple_response


class TaskResumeResponse(BaseModel):
    __root__: simple_response.SimpleResponse = Field(
        ...,
        description="Response to a request to resume a task",
        title="Task Resume Response",
    )
