# generated by datamodel-codegen:
#   filename:  rewind_task_response.schema.json

from __future__ import annotations

from pydantic import BaseModel, Field

from ..simple_response import schema


class TaskRewindResponse(BaseModel):
    __root__: schema.SimpleResponse = Field(
        ...,
        description="Response to a request to rewind a task",
        title="Task Rewind Response",
    )
