# generated by datamodel-codegen:
#   filename:  rewind_task_request.json

from __future__ import annotations

from pydantic import BaseModel, Field, conint
from typing_extensions import Literal


class TaskRewindRequest(BaseModel):
    type: Literal["rewind_task_request"] = Field(
        ..., description="Indicate that this is a task rewind request"
    )
    task_id: str = Field(
        ..., description="Specify the ID of the task that should rewind"
    )
    phase_id: conint(ge=0) = Field(
        ...,
        description="Specify the phase that should be rewound to. The task will restart at the beginning of this phase.",
    )
