# generated by datamodel-codegen:
#   filename:  rewind_task_response.json

from __future__ import annotations

from pydantic import BaseModel, Field

from . import simple_response


class TaskRewindResponse(BaseModel):
    __root__: simple_response.SimpleResponse = Field(
        ...,
        description="Response to a request to rewind a task",
        title="Task Rewind Response",
    )
