# generated by datamodel-codegen:
#   filename:  robot_commission_response.json

from __future__ import annotations

from typing import List, Optional, Union

from pydantic import BaseModel, Field, RootModel
from typing_extensions import Literal

from . import error


class Result1(BaseModel):
    success: Literal[True]


class Result2(BaseModel):
    success: Literal[False]
    errors: Optional[List[error.Error]] = Field(
        default=None, description="Any error messages explaining why the request failed"
    )


class Result(RootModel[Union[Result1, Result2]]):
    root: Union[Result1, Result2]


class RobotCommissionResponse(BaseModel):
    commission: Result
    pending_dispatch_tasks_policy: Optional[Result] = None
    pending_direct_tasks_policy: Optional[Result] = None
