# generated by datamodel-codegen:
#   filename:  robot_task_response.json

from __future__ import annotations

from pydantic import BaseModel, Field

from . import dispatch_task_response


class RobotTaskResponse(BaseModel):
    __root__: dispatch_task_response.TaskDispatchResponse = Field(
        ..., description="Response to a robot task request", title="Robot Task Response"
    )
