# generated by datamodel-codegen:
#   filename:  robot_commission_request.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class Commission(BaseModel):
    dispatch_tasks: Optional[bool] = Field(
        None,
        description="Should the robot accept dispatched tasks, true/false. Leave unset to not change the robot's current value.",
    )
    direct_tasks: Optional[bool] = Field(
        None,
        description="Should the robot accept direct task requests, true/false. Leave unset to not change the robot's current value.",
    )
    idle_behavior: Optional[bool] = Field(
        None,
        description="Should the robot perform its idle behavior, true/false. Leave unset to not change the robot's current value.",
    )


class RobotCommissionRequest(BaseModel):
    type: str = Field(
        ..., description="Indicate that this is a robot commission request"
    )
    robot: str = Field(..., description="The name of the robot")
    fleet: str = Field(..., description="The fleet the robot belongs to")
    commission: Commission = Field(
        ..., description="Describe the requested commission for this robot"
    )
    reassign_tasks: Optional[bool] = Field(
        None,
        description="Should the tasks of the decommissioned robot be reassigned to other robots? If unset, it will be treated as true.",
    )
