# generated by datamodel-codegen:
#   filename:  robot_task_request.json

from __future__ import annotations

from pydantic import BaseModel, Field

from . import task_request


class RobotTaskRequest(BaseModel):
    type: str = Field(..., description="Indicate that this is a task dispatch request")
    robot: str = Field(..., description="The name of the robot")
    fleet: str = Field(..., description="The fleet the robot belongs to")
    request: task_request.TaskRequest
