# generated by datamodel-codegen:
#   filename:  robot_commission_request.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field

from . import commission


class RobotCommissionRequest(BaseModel):
    type: str = Field(
        ..., description="Indicate that this is a robot commission request"
    )
    robot: str = Field(..., description="The name of the robot")
    fleet: str = Field(..., description="The fleet the robot belongs to")
    commission: commission.Commission
    reassign_tasks: Optional[bool] = Field(
        None,
        description="Should the tasks of the decommissioned robot be reassigned to other robots? If unset, it will be treated as true.",
    )
