# generated by datamodel-codegen:
#   filename:  simple_response.json

from __future__ import annotations

from typing import List, Union

from pydantic import BaseModel, Field, RootModel
from typing_extensions import Literal

from . import error


class Success(RootModel[Literal[True]]):
    root: Literal[True] = Field(..., description="The request was successful")


class Failure(RootModel[Literal[False]]):
    root: Literal[False] = Field(..., description="The request failed")


class SimpleResponse1(BaseModel):
    success: Success


class SimpleResponse2(BaseModel):
    success: Failure
    errors: List[error.Error] = Field(
        ..., description="If the request failed, these error messages will explain why"
    )


class SimpleResponse(RootModel[Union[SimpleResponse1, SimpleResponse2]]):
    root: Union[SimpleResponse1, SimpleResponse2] = Field(
        ...,
        description="Template for defining a response message that only indicates success and describes any errors",
        title="Simple Response",
    )
