# generated by datamodel-codegen:
#   filename:  simple_response.schema.json

from __future__ import annotations

from typing import List, Union

from pydantic import BaseModel, Field

from ..error import schema


class Failure(BaseModel):
    __root__: bool = Field(..., description="The request failed")


class Success(BaseModel):
    __root__: bool = Field(..., description="The request was successful")


class SimpleResponseItem(BaseModel):
    success: Success


class SimpleResponseItem1(BaseModel):
    success: Failure
    errors: List[schema.Error] = Field(
        ..., description="If the request failed, these error messages will explain why"
    )


class SimpleResponse(BaseModel):
    __root__: Union[SimpleResponseItem, SimpleResponseItem1] = Field(
        ...,
        description="Template for defining a response message that only indicates success and describes any errors",
        title="Simple Response",
    )
