# generated by datamodel-codegen:
#   filename:  skip_phase_request.json

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field, conint
from typing_extensions import Literal


class TaskPhaseSkipRequest(BaseModel):
    type: Literal["skip_phase_request"] = Field(
        ..., description="Indicate that this is a phase skip request"
    )
    task_id: str = Field(
        ..., description="Specify the task ID whose phase should be skipped"
    )
    phase_id: conint(ge=0) = Field(
        ..., description="Specify the phase that should be skipped"
    )
    labels: Optional[List[str]] = Field(
        default=None, description="Labels to describe the purpose of the skip"
    )
