# generated by datamodel-codegen:
#   filename:  skip_phase_response.schema.json

from __future__ import annotations

from pydantic import BaseModel, Field

from ..token_response import schema


class SkipPhaseResponse(BaseModel):
    __root__: schema.TokenResponse = Field(
        ...,
        description="Response to a request for a phase to be skipped",
        title="Skip Phase Response",
    )
