# generated by datamodel-codegen:
#   filename:  task_log_update.schema.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field

from ..task_log import schema


class TaskEventLogUpdate(BaseModel):
    type: Optional[str] = Field(
        None, description="Indicate that this is an event log update"
    )
    data: Optional[schema.TaskEventLog] = None
