# generated by datamodel-codegen:
#   filename:  task_state_update.schema.json

from __future__ import annotations

from pydantic import BaseModel, Field

from ..task_state import schema


class TaskStateUpdate(BaseModel):
    type: str = Field(..., description="Indicate that this is a task state update")
    data: schema.TaskState
