# generated by datamodel-codegen:
#   filename:  task_log_update.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field

from . import task_log


class TaskEventLogUpdate(BaseModel):
    type: Optional[str] = Field(
        None, description="Indicate that this is an event log update"
    )
    data: Optional[task_log.TaskEventLog] = None
