# generated by datamodel-codegen:
#   filename:  task_favorite_request.json

from __future__ import annotations

from pydantic import BaseModel, Field
from typing_extensions import Literal

from . import task_favorite


class TaskFavoriteRequest(BaseModel):
    type: Literal["task_favorite_request"] = Field(
        ..., description="Indicate that this is a task favorite request"
    )
    request: task_favorite.TaskFavorite
