# generated by datamodel-codegen:
#   filename:  task_state_update.json

from __future__ import annotations

from pydantic import BaseModel, Field

from . import task_state


class TaskStateUpdate(BaseModel):
    type: str = Field(..., description="Indicate that this is a task state update")
    data: task_state.TaskState
