# generated by datamodel-codegen:
#   filename:  task_discovery_request.json

from __future__ import annotations

from pydantic import BaseModel, Field
from typing_extensions import Literal


class TaskDiscoveryRequest(BaseModel):
    type: Literal["task_discovery_request"] = Field(
        ..., description="Indicate that this is a task discovery request"
    )
