# generated by datamodel-codegen:
#   filename:  task_log_update.json

from __future__ import annotations

from pydantic import BaseModel, Field
from typing_extensions import Literal

from . import task_log


class TaskEventLogUpdate(BaseModel):
    type: Literal["task_log_update"] = Field(
        ..., description="Indicate that this is an event log update"
    )
    data: task_log.TaskEventLog
