# generated by datamodel-codegen:
#   filename:  task_log_response.json

from __future__ import annotations

from typing import List, Union

from pydantic import BaseModel, Field, RootModel
from typing_extensions import Literal

from . import error, task_log


class Success(RootModel[Literal[True]]):
    root: Literal[True] = Field(..., description="The request was successful")


class Failure(RootModel[Literal[False]]):
    root: Literal[False] = Field(..., description="The request failed")


class TaskLogResponse1(BaseModel):
    success: Success
    data: task_log.TaskEventLog


class TaskLogResponse2(BaseModel):
    success: Failure
    errors: List[error.Error] = Field(
        ..., description="Any error messages explaining why the request failed"
    )


class TaskLogResponse(RootModel[Union[TaskLogResponse1, TaskLogResponse2]]):
    root: Union[TaskLogResponse1, TaskLogResponse2] = Field(
        ..., description="Responding to a task log request", title="Task Log Response"
    )
