# generated by datamodel-codegen:
#   filename:  task_log_response.schema.json

from __future__ import annotations

from typing import List, Union

from pydantic import BaseModel, Field

from ..error import schema as schema_1
from ..task_log import schema


class Failure(BaseModel):
    __root__: bool = Field(..., description="The request failed")


class Success(BaseModel):
    __root__: bool = Field(..., description="The request was successful")


class TaskLogResponseItem(BaseModel):
    success: Success
    data: schema.TaskEventLog


class TaskLogResponseItem1(BaseModel):
    success: Failure
    errors: List[schema_1.Error] = Field(
        ..., description="Any error messages explaining why the request failed"
    )


class TaskLogResponse(BaseModel):
    __root__: Union[TaskLogResponseItem, TaskLogResponseItem1] = Field(
        ..., description="Responding to a task log request", title="Task Log Response"
    )
