# generated by datamodel-codegen:
#   filename:  task_log_response.json

from __future__ import annotations

from typing import List, Union

from pydantic import BaseModel, Field

from . import error, task_log


class Failure(BaseModel):
    __root__: bool = Field(..., description="The request failed")


class Success(BaseModel):
    __root__: bool = Field(..., description="The request was successful")


class TaskLogResponseItem(BaseModel):
    success: Success
    data: task_log.TaskEventLog


class TaskLogResponseItem1(BaseModel):
    success: Failure
    errors: List[error.Error] = Field(
        ..., description="Any error messages explaining why the request failed"
    )


class TaskLogResponse(BaseModel):
    __root__: Union[TaskLogResponseItem, TaskLogResponseItem1] = Field(
        ..., description="Responding to a task log request", title="Task Log Response"
    )
