# generated by datamodel-codegen:
#   filename:  task_favorite.json

from __future__ import annotations

from typing import Any, Dict, Optional

from pydantic import BaseModel, Field


class TaskFavorite(BaseModel):
    id: Optional[str] = None
    name: str = Field(..., description="The favorite name")
    unix_millis_earliest_start_time: Optional[int] = None
    priority: Optional[Dict[str, Any]] = None
    category: str
    description: Any = Field(
        ..., description="A description of the task. Task properties by category"
    )
    user: Optional[str] = None
