# generated by datamodel-codegen:
#   filename:  task_request.json

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class TaskRequest(BaseModel):
    unix_millis_earliest_start_time: Optional[int] = Field(
        None, description="(Optional) The earliest time that this task may start"
    )
    priority: Optional[Dict[str, Any]] = Field(
        None,
        description="(Optional) The priority of this task. This must match a priority schema supported by a fleet.",
    )
    category: str
    description: Any = Field(
        ...,
        description="A description of the task. This must match a schema supported by a fleet for the category of this task request.",
    )
    labels: Optional[List[str]] = Field(
        None, description="Labels to describe the purpose of the task dispatch request"
    )
