# generated by datamodel-codegen:
#   filename:  task_request.json

from __future__ import annotations

from typing import Any, Dict, Optional

from pydantic import BaseModel, Field


class Description(BaseModel):
    category: str


class TaskRequest(BaseModel):
    unix_millis_earliest_start_time: Optional[int] = Field(
        None, description="(Optional) The earliest time that this task may start"
    )
    priority: Optional[Dict[str, Any]] = Field(
        None,
        description="(Optional) The priority of this task. This must match a priority schema supported by a fleet.",
    )
    description: Description = Field(
        ...,
        description="A description of the task. This must match a schema supported by a fleet.",
    )
