# generated by datamodel-codegen:
#   filename:  task_discovery_request.json

from __future__ import annotations

from pydantic import BaseModel, Field


class TaskDiscoveryRequest(BaseModel):
    type: str = Field(..., description="Indicate that this is a task discovery request")
