# generated by datamodel-codegen:
#   filename:  task_favorite_response.json

from __future__ import annotations

from typing import List, Optional, Union

from pydantic import BaseModel, Field
from typing_extensions import Literal

from . import error, task_favorite


class TaskFavoriteResponseItem(BaseModel):
    success: Literal[True]
    data: task_favorite.TaskFavorite


class TaskFavoriteResponseItem1(BaseModel):
    success: Literal[False]
    errors: Optional[List[error.Error]] = Field(
        None, description="Any error messages explaining why the request failed"
    )


class TaskFavoriteResponse(BaseModel):
    __root__: Union[TaskFavoriteResponseItem, TaskFavoriteResponseItem1] = Field(
        ...,
        description="Response to a task dispatch request",
        title="Task Dispatch Response",
    )
