# generated by datamodel-codegen:
#   filename:  transformation_2D.json

from __future__ import annotations

from pydantic import BaseModel


class Transformation2D(BaseModel):
    target_map: str
    ref_map: str
    x: float
    y: float
    yaw: float
    scale: float
