# generated by datamodel-codegen:
#   filename:  undo_skip_phase_response.schema.json

from __future__ import annotations

from pydantic import BaseModel, Field

from ..simple_response import schema


class UndoPhaseSkipResponse(BaseModel):
    __root__: schema.SimpleResponse = Field(
        ...,
        description="Response to an undo phase skip request",
        title="Undo Phase Skip Response",
    )
