export enum Reports {
  queryAllLogs = 'queryAllLogs',
  showChargerStateReport = 'showChargerStateReport',
  showDispenserStateReport = 'showDispenserStateReport',
  showDoorStateReport = 'showDoorStateReport',
  showFleetStateReport = 'showFleetStateReport',
  showHealthReport = 'showHealthReport',
  showIngestorStateReport = 'showIngestorStateReport',
  showLiftStateReport = 'showLiftStateReport',
  showNegotiationsReport = 'showNegotiationsReport',
  showRobotStateReport = 'showRobotStateReport',
  showRobotMotionPlansReport = 'showRobotMotionPlansReport',
  showRobotActionReport = 'showRobotActionReport',
  showTasksReport = 'showTasksReport',
  showUserActionsReport = 'showUserActionsReport',
  showLoginsReport = 'showLoginsReport',
  showLogoutsReport = 'showLogoutsReport',
  showLoginFailuresReport = 'showLoginFailuresReport',
  showWorkCellStatesReport = 'showWorkCellStatesReport',
}
