# generated by datamodel-codegen:
#   filename:  event_description_Sequence.json

from __future__ import annotations

from typing import Any, List, Optional, Union

from pydantic import BaseModel, Field


class ActivityArrayItem(BaseModel):
    category: Optional[str] = Field(None, description="The category of the activity")
    description: Optional[Any] = Field(
        None,
        description="A description of the activity. This must match a schema supported by a fleet for the activity category.",
    )


class ActivityArray(BaseModel):
    __root__: List[ActivityArrayItem] = Field(..., ge=1.0)


class ActivitySequenceItem(BaseModel):
    activities: ActivityArray
    category: Optional[str] = Field(
        None, description="Customize the category display for this sequence"
    )
    detail: Optional[Any] = Field(
        None, description="Customize the detail display for this sequence"
    )


class ActivitySequence(BaseModel):
    __root__: Union[ActivityArray, ActivitySequenceItem] = Field(
        ..., description="A sequence of activities", title="Activity Sequence"
    )
