# generated by datamodel-codegen:
#   filename:  event_description_Clean.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class CleanEvent(BaseModel):
    zone: str
    type: Optional[str] = None
