# generated by datamodel-codegen:
#   filename:  event_description_PayloadTransfer.json

from __future__ import annotations

from typing import List, Optional, Union

from pydantic import BaseModel, conint

from . import Place


class PayloadComponent(BaseModel):
    sku: str
    quantity: conint(ge=0)
    compartment: Optional[str] = None


class ItemTransferEventDescription(BaseModel):
    place: Place.PlaceDescription
    handler: Optional[str] = None
    payload: Union[PayloadComponent, List[PayloadComponent]]
