# generated by datamodel-codegen:
#   filename:  event_description_DropOff.json

from __future__ import annotations

from pydantic import Field, RootModel

from . import event_description_PayloadTransfer


class DropOffEventDescription(
    RootModel[event_description_PayloadTransfer.ItemTransferEventDescription]
):
    root: event_description_PayloadTransfer.ItemTransferEventDescription = Field(
        ..., title="Drop Off Event Description"
    )
