# generated by datamodel-codegen:
#   filename:  event_description_PickUp.json

from __future__ import annotations

from pydantic import Field, RootModel

from . import event_description_PayloadTransfer


class PickUpEventDescription(
    RootModel[event_description_PayloadTransfer.ItemTransferEventDescription]
):
    root: event_description_PayloadTransfer.ItemTransferEventDescription = Field(
        ..., title="Pick Up Event Description"
    )
