# generated by datamodel-codegen:
#   filename:  event_description__pickup.json

from __future__ import annotations

from pydantic import Field, RootModel

from . import event_description__payload_transfer


class PickUpEventDescription(
    RootModel[event_description__payload_transfer.ItemTransferEventDescription]
):
    root: event_description__payload_transfer.ItemTransferEventDescription = Field(
        ..., title="Pick Up Event Description"
    )
