# generated by datamodel-codegen:
#   filename:  task_description_Clean.json

from __future__ import annotations

from pydantic import BaseModel, Field

from . import event_description_Clean


class CleanTask(BaseModel):
    __root__: event_description_Clean.CleanEvent = Field(
        ..., description="Clean a zone", title="Clean Task"
    )
