# generated by datamodel-codegen:
#   filename:  task_description_Delivery.json

from __future__ import annotations

from pydantic import BaseModel

from . import event_description_DropOff, event_description_PickUp


class DeliveryTaskDescription(BaseModel):
    pickup: event_description_PickUp.PickUpEventDescription
    dropoff: event_description_DropOff.DropOffEventDescription
