# generated by datamodel-codegen:
#   filename:  task_description__patrol.json

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field, conint

from . import place


class PatrolTaskDescription(BaseModel):
    places: List[place.PlaceDescription] = Field(
        ..., description="A list of which places to patrol between"
    )
    rounds: Optional[conint(ge=1)] = Field(
        default=None,
        description="How many times the patrol should be performed. By default this is 1.",
    )
