name: Reporting e2e
description: Run reporting e2e tests
runs:
  using: composite
  steps:
    - run: |
        npm config set unsafe-perm
        npm install -g lerna@4
        lerna bootstrap --scope=reporting-e2e
        docker pull quay.io/keycloak/keycloak:12.0.4
        npm test || npm test
      env:
        E2E_DOCKER_NETWORK: ${{job.container.network}}
        REACT_APP_AUTH_PROVIDER: keycloak
        # need to use the internal port because we are connecting from within the same network
        REACT_APP_KEYCLOAK_CONFIG: '{ "realm": "master", "clientId": "reporting", "url": "http://rmf-web_keycloak_1:8080/auth" }'
      working-directory: packages/reporting-e2e
      shell: bash
