name: Reporting e2e
description: Run reporting e2e tests
runs:
  using: composite
  steps:
    - run: |
        ../../scripts/bootstrap.sh reporting-e2e
        npm i -g npm@latest
        npm test || npm test
      working-directory: packages/reporting-e2e
      shell: bash
