from .building_map import BuildingMapRouter
from .chargers import ChargersRouter
from .dispensers import DispensersRouter
from .doors import DoorsRouter
from .fire_alarm import FireAlarmRouter
from .fleets import FleetsRouter
from .ingestors import IngestorsRouter
from .lifts import LiftsRouter
from .tasks import TasksRouter
