from api_server.routes.admin import admin_router
from api_server.routes.building_map import BuildingMapRouter
from api_server.routes.dispensers import DispensersRouter
from api_server.routes.doors import DoorsRouter
from api_server.routes.fleets import FleetsRouter
from api_server.routes.ingestors import IngestorsRouter
from api_server.routes.lifts import LiftsRouter
from api_server.routes.main import main_router
from api_server.routes.tasks import TasksRouter
