from .admin import admin_router
from .building_map import BuildingMapRouter
from .dispensers import DispensersRouter
from .doors import DoorsRouter
from .fleets import FleetsRouter
from .ingestors import IngestorsRouter
from .lifts import LiftsRouter
from .main import main_router
from .tasks import TasksRouter
