version: '3'
services:
  auth:
    build:
      context: .
      dockerfile: auth.Dockerfile
    image: romi-dashboard/auth
    ports:
      - 8080:8080
  e2e:
    build:
      context: ..
      dockerfile: docker/e2e.Dockerfile
    image: docker.pkg.github.com/osrf/romi-dashboard/e2e
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/root/romi-dashboard
    working_dir: /root/romi-dashboard
    environment:
      CI: 1
      CHROME_BIN: /chrome-no-sandbox
    ipc: host
    network_mode: host
    privileged: true
    command: npm run test:e2e
  dev:
    image: docker.pkg.github.com/osrf/romi-dashboard/e2e
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/root/romi-dashboard
    working_dir: /root/romi-dashboard
    ipc: host
    network_mode: host
    privileged: true
    command: bash -c 'BROWSER=none npm start'
