version: "3"
services:
  trajectory-server:
    image: docker.pkg.github.com/osrf/romi-dashboard/rmf:nightly
    command: ros2 launch visualizer server.xml
    ports:
      - 8006:8006
  office-demo:

    image: docker.pkg.github.com/osrf/romi-dashboard/rmf:nightly
    command: ros2 launch demos office.launch.xml headless:=true
  soss:
    image: docker.pkg.github.com/osrf/romi-dashboard/rmf:nightly
    command: soss /root/romi-dashboard/e2e/soss.yaml
    volumes:
      - ../e2e:/root/romi-dashboard/e2e
    ports:
      - 50001:50001
  auth:
    build:
      context: .
      dockerfile: auth.Dockerfile
    image: romi-dashboard/auth
    ports:
      - 8080:8080
  probe-rmf:
    image: docker.pkg.github.com/osrf/romi-dashboard/rmf:nightly
    command: bash -c 'while [ ! $$(ros2 node list | grep rmf_traffic) ]; do sleep 1; done;'
