version: "3"
services:
  trajectory-server:
    image: rmf/rmf
    command: ros2 launch visualizer server.xml
    ports:
      - 8006:8006
  office-demo:
    image: rmf/rmf
    command: ros2 launch demos office.launch.xml headless:=true
  soss:
    build:
      context: ..
      dockerfile: docker/soss.Dockerfile
    image: romi-dashboard/soss
    ports:
      - 50001:50001
  auth:
    build:
      context: .
      dockerfile: auth.Dockerfile
    image: romi-dashboard/auth
    ports:
      - 8080:8080
