version: '3'
services:
  auth:
    build:
      context: .
      dockerfile: auth.Dockerfile
    image: romi-dashboard/auth
    ports:
      - 8080:8080
  e2e:
    build:
      context: ..
      dockerfile: docker/e2e.Dockerfile
    image: docker.pkg.github.com/osrf/romi-dashboard/e2e:test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/root/romi-dashboard
    working_dir: /root/romi-dashboard
    environment:
      CI: 1
      CHROME_BIN: /chrome-no-sandbox
    ipc: host
    network_mode: host
    privileged: true
    # need owner to be root for git ls-remote to work for some reason
    command: bash -c 'chown -R root . && npm ci --unsafe-perm && (npm run test:e2e || npm run test:e2e || npm run test:e2e)'
  unit-test:
    image: docker.pkg.github.com/osrf/romi-dashboard/e2e
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/root/romi-dashboard
    working_dir: /root/romi-dashboard
    environment:
      CI: 1
    ipc: host
    network_mode: host
    privileged: true
    # need owner to be root for git ls-remote to work for some reason
    command: bash -c 'chown -R root . && npm ci --unsafe-perm && npm run test'
  dev:
    image: docker.pkg.github.com/osrf/romi-dashboard/e2e
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/root/romi-dashboard
    working_dir: /root/romi-dashboard
    ipc: host
    network_mode: host
    privileged: true
    command: bash -c 'BROWSER=none npm start'
