#!/bin/bash

export TS_NODE_PROJECT=e2e/tsconfig.json
export REACT_APP_SOSS_SERVER=wss://localhost:50001
export REACT_APP_SOSS_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoicm9taS1kYXNoYm9hcmQiLCJpYXQiOjE1ODMyODYyMTV9.x9aNjcLujQPHchWEsbrRbvctmnGQtEzw-81X0aPIE-Y
export REACT_APP_TRAJECTORY_SERVER=ws://localhost:8006