/* tslint:disable */
/* eslint-disable */
/**
 * RMF API Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface AffineImage
 */
export interface AffineImage {
  /**
   *
   * @type {string}
   * @memberof AffineImage
   */
  name?: any;
  /**
   *
   * @type {number}
   * @memberof AffineImage
   */
  x_offset?: any;
  /**
   *
   * @type {number}
   * @memberof AffineImage
   */
  y_offset?: any;
  /**
   *
   * @type {number}
   * @memberof AffineImage
   */
  yaw?: any;
  /**
   *
   * @type {number}
   * @memberof AffineImage
   */
  scale?: any;
  /**
   *
   * @type {string}
   * @memberof AffineImage
   */
  encoding?: any;
  /**
   *
   * @type {string}
   * @memberof AffineImage
   */
  data: any;
}
