/* tslint:disable */
/* eslint-disable */
/**
 * RMF API Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface BuildingMap
 */
export interface BuildingMap {
  /**
   *
   * @type {string}
   * @memberof BuildingMap
   */
  name?: any;
  /**
   *
   * @type {Array&lt;Level&gt;}
   * @memberof BuildingMap
   */
  levels: any;
  /**
   *
   * @type {Array&lt;Lift&gt;}
   * @memberof BuildingMap
   */
  lifts?: any;
}
