/* tslint:disable */
/* eslint-disable */
/**
 * RMF API Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ChargerState
 */
export interface ChargerState {
  /**
   *
   * @type {Time}
   * @memberof ChargerState
   */
  charger_time?: any;
  /**
   *
   * @type {number}
   * @memberof ChargerState
   */
  state?: any;
  /**
   *
   * @type {string}
   * @memberof ChargerState
   */
  charger_name?: any;
  /**
   *
   * @type {string}
   * @memberof ChargerState
   */
  error_message?: any;
  /**
   *
   * @type {string}
   * @memberof ChargerState
   */
  request_id?: any;
  /**
   *
   * @type {string}
   * @memberof ChargerState
   */
  robot_fleet?: any;
  /**
   *
   * @type {string}
   * @memberof ChargerState
   */
  robot_name?: any;
  /**
   *
   * @type {Duration}
   * @memberof ChargerState
   */
  time_to_fully_charged?: any;
}
