/* tslint:disable */
/* eslint-disable */
/**
 * RMF API Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ChargerRequest
 */
export interface ChargerRequest {
  /**
   *
   * @type {string}
   * @memberof ChargerRequest
   */
  charger_name?: any;
  /**
   *
   * @type {string}
   * @memberof ChargerRequest
   */
  fleet_name?: any;
  /**
   *
   * @type {string}
   * @memberof ChargerRequest
   */
  robot_name?: any;
  /**
   *
   * @type {Duration}
   * @memberof ChargerRequest
   */
  start_timeout?: any;
  /**
   *
   * @type {string}
   * @memberof ChargerRequest
   */
  request_id?: any;
}
