/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface DeliveryTaskDescription
 */
export interface DeliveryTaskDescription {
  /**
   *
   * @type {string}
   * @memberof DeliveryTaskDescription
   */
  pickup_place_name: any;
  /**
   *
   * @type {string}
   * @memberof DeliveryTaskDescription
   */
  pickup_dispenser: any;
  /**
   *
   * @type {string}
   * @memberof DeliveryTaskDescription
   */
  dropoff_ingestor: any;
  /**
   *
   * @type {string}
   * @memberof DeliveryTaskDescription
   */
  dropoff_place_name: any;
}
