/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Delivery
 */
export interface Delivery {
  /**
   *
   * @type {string}
   * @memberof Delivery
   */
  taskId?: any;
  /**
   *
   * @type {Array&lt;DispenserRequestItem&gt;}
   * @memberof Delivery
   */
  items?: any;
  /**
   *
   * @type {string}
   * @memberof Delivery
   */
  pickupPlaceName?: any;
  /**
   *
   * @type {string}
   * @memberof Delivery
   */
  pickupDispenser?: any;
  /**
   *
   * @type {Behavior}
   * @memberof Delivery
   */
  pickupBehavior?: any;
  /**
   *
   * @type {string}
   * @memberof Delivery
   */
  dropoffPlaceName?: any;
  /**
   *
   * @type {string}
   * @memberof Delivery
   */
  dropoffIngestor?: any;
  /**
   *
   * @type {Behavior}
   * @memberof Delivery
   */
  dropoffBehavior?: any;
}
