/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Delivery
 */
export interface Delivery {
  /**
   *
   * @type {string}
   * @memberof Delivery
   */
  task_id?: any;
  /**
   *
   * @type {Array&lt;DispenserRequestItem&gt;}
   * @memberof Delivery
   */
  items?: any;
  /**
   *
   * @type {string}
   * @memberof Delivery
   */
  pickup_place_name?: any;
  /**
   *
   * @type {string}
   * @memberof Delivery
   */
  pickup_dispenser?: any;
  /**
   *
   * @type {Behavior}
   * @memberof Delivery
   */
  pickup_behavior?: any;
  /**
   *
   * @type {string}
   * @memberof Delivery
   */
  dropoff_place_name?: any;
  /**
   *
   * @type {string}
   * @memberof Delivery
   */
  dropoff_ingestor?: any;
  /**
   *
   * @type {Behavior}
   * @memberof Delivery
   */
  dropoff_behavior?: any;
}
