/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface DispenserRequestItem
 */
export interface DispenserRequestItem {
  /**
   *
   * @type {string}
   * @memberof DispenserRequestItem
   */
  type_guid?: any;
  /**
   *
   * @type {number}
   * @memberof DispenserRequestItem
   */
  quantity?: any;
  /**
   *
   * @type {string}
   * @memberof DispenserRequestItem
   */
  compartment_name?: any;
}
