/* tslint:disable */
/* eslint-disable */
/**
 * RMF API Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Door
 */
export interface Door {
  /**
   *
   * @type {string}
   * @memberof Door
   */
  name?: any;
  /**
   *
   * @type {number}
   * @memberof Door
   */
  v1_x?: any;
  /**
   *
   * @type {number}
   * @memberof Door
   */
  v1_y?: any;
  /**
   *
   * @type {number}
   * @memberof Door
   */
  v2_x?: any;
  /**
   *
   * @type {number}
   * @memberof Door
   */
  v2_y?: any;
  /**
   *
   * @type {number}
   * @memberof Door
   */
  door_type?: any;
  /**
   *
   * @type {number}
   * @memberof Door
   */
  motion_range?: any;
  /**
   *
   * @type {number}
   * @memberof Door
   */
  motion_direction?: any;
}
