/* tslint:disable */
/* eslint-disable */
/**
 * RMF API Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Abstract base class for generic types.  A generic type is typically declared by inheriting from this class parameterized with one or more type variables. For example, a generic mapping type might be defined as::    class Mapping(Generic[KT, VT]):       def __getitem__(self, key: KT) -> VT:           ...       # Etc.  This class can then be used as follows::    def lookup_name(mapping: Mapping[KT, VT], key: KT, default: VT) -> VT:       try:           return mapping[key]       except KeyError:           return default
 * @export
 * @interface GetTasksResponse
 */
export interface GetTasksResponse {
  /**
   *
   * @type {Array&lt;Task&gt;}
   * @memberof GetTasksResponse
   */
  items: any;
  /**
   *
   * @type {number}
   * @memberof GetTasksResponse
   */
  total_count: any;
}
