/* tslint:disable */
/* eslint-disable */
/**
 * RMF API Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface GraphNode
 */
export interface GraphNode {
  /**
   *
   * @type {number}
   * @memberof GraphNode
   */
  x?: any;
  /**
   *
   * @type {number}
   * @memberof GraphNode
   */
  y?: any;
  /**
   *
   * @type {string}
   * @memberof GraphNode
   */
  name?: any;
  /**
   *
   * @type {Array&lt;Param&gt;}
   * @memberof GraphNode
   */
  params?: any;
}
