/* tslint:disable */
/* eslint-disable */
/**
 * RMF API Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface IngestorState
 */
export interface IngestorState {
  /**
   *
   * @type {Time}
   * @memberof IngestorState
   */
  time?: any;
  /**
   *
   * @type {string}
   * @memberof IngestorState
   */
  guid?: any;
  /**
   *
   * @type {number}
   * @memberof IngestorState
   */
  mode?: any;
  /**
   *
   * @type {Array&lt;string&gt;}
   * @memberof IngestorState
   */
  request_guid_queue?: any;
  /**
   *
   * @type {number}
   * @memberof IngestorState
   */
  seconds_remaining?: any;
}
