/* tslint:disable */
/* eslint-disable */
/**
 * RMF API Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Lift
 */
export interface Lift {
  /**
   *
   * @type {string}
   * @memberof Lift
   */
  name?: any;
  /**
   *
   * @type {Array&lt;string&gt;}
   * @memberof Lift
   */
  levels?: any;
  /**
   *
   * @type {Array&lt;Door&gt;}
   * @memberof Lift
   */
  doors?: any;
  /**
   *
   * @type {Graph}
   * @memberof Lift
   */
  wall_graph?: any;
  /**
   *
   * @type {number}
   * @memberof Lift
   */
  ref_x?: any;
  /**
   *
   * @type {number}
   * @memberof Lift
   */
  ref_y?: any;
  /**
   *
   * @type {number}
   * @memberof Lift
   */
  ref_yaw?: any;
  /**
   *
   * @type {number}
   * @memberof Lift
   */
  width?: any;
  /**
   *
   * @type {number}
   * @memberof Lift
   */
  depth?: any;
}
