/* tslint:disable */
/* eslint-disable */
/**
 * RMF API Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Loop
 */
export interface Loop {
  /**
   *
   * @type {string}
   * @memberof Loop
   */
  task_id?: any;
  /**
   *
   * @type {string}
   * @memberof Loop
   */
  robot_type?: any;
  /**
   *
   * @type {number}
   * @memberof Loop
   */
  num_loops?: any;
  /**
   *
   * @type {string}
   * @memberof Loop
   */
  start_name?: any;
  /**
   *
   * @type {string}
   * @memberof Loop
   */
  finish_name?: any;
}
