/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface LoopTaskDescription
 */
export interface LoopTaskDescription {
  /**
   *
   * @type {number}
   * @memberof LoopTaskDescription
   */
  num_loops: any;
  /**
   *
   * @type {string}
   * @memberof LoopTaskDescription
   */
  start_name: any;
  /**
   *
   * @type {string}
   * @memberof LoopTaskDescription
   */
  finish_name: any;
}
