/* tslint:disable */
/* eslint-disable */
/**
 * RMF API Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Param
 */
export interface Param {
  /**
   *
   * @type {string}
   * @memberof Param
   */
  name?: any;
  /**
   *
   * @type {number}
   * @memberof Param
   */
  type?: any;
  /**
   *
   * @type {number}
   * @memberof Param
   */
  value_int?: any;
  /**
   *
   * @type {number}
   * @memberof Param
   */
  value_float?: any;
  /**
   *
   * @type {string}
   * @memberof Param
   */
  value_string?: any;
  /**
   *
   * @type {boolean}
   * @memberof Param
   */
  value_bool?: any;
}
