/* tslint:disable */
/* eslint-disable */
/**
 * RMF API Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Place
 */
export interface Place {
  /**
   *
   * @type {string}
   * @memberof Place
   */
  name?: any;
  /**
   *
   * @type {number}
   * @memberof Place
   */
  x?: any;
  /**
   *
   * @type {number}
   * @memberof Place
   */
  y?: any;
  /**
   *
   * @type {number}
   * @memberof Place
   */
  yaw?: any;
  /**
   *
   * @type {number}
   * @memberof Place
   */
  position_tolerance?: any;
  /**
   *
   * @type {number}
   * @memberof Place
   */
  yaw_tolerance?: any;
}
