/* tslint:disable */
/* eslint-disable */
/**
 * RMF API Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface PostRolePermissions
 */
export interface PostRolePermissions {
  /**
   *
   * @type {string}
   * @memberof PostRolePermissions
   */
  action: any;
  /**
   *
   * @type {string}
   * @memberof PostRolePermissions
   */
  authz_grp?: any;
}
