/* tslint:disable */
/* eslint-disable */
/**
 * RMF API Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Station
 */
export interface Station {
  /**
   *
   * @type {string}
   * @memberof Station
   */
  task_id?: any;
  /**
   *
   * @type {string}
   * @memberof Station
   */
  robot_type?: any;
  /**
   *
   * @type {string}
   * @memberof Station
   */
  place_name?: any;
}
