/* tslint:disable */
/* eslint-disable */
/**
 * RMF API Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface SubmitTask
 */
export interface SubmitTask {
  /**
   *
   * @type {TaskTypeEnum}
   * @memberof SubmitTask
   */
  task_type: any;
  /**
   *
   * @type {number}
   * @memberof SubmitTask
   */
  start_time: any;
  /**
   *
   * @type {number}
   * @memberof SubmitTask
   */
  priority?: any;
  /**
   *
   * @type {CleanTaskDescription | LoopTaskDescription | DeliveryTaskDescription}
   * @memberof SubmitTask
   */
  description: any;
}
