/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface TaskSummary
 */
export interface TaskSummary {
  /**
   *
   * @type {string}
   * @memberof TaskSummary
   */
  fleetName?: any;
  /**
   *
   * @type {string}
   * @memberof TaskSummary
   */
  taskId?: any;
  /**
   *
   * @type {TaskProfile}
   * @memberof TaskSummary
   */
  taskProfile?: any;
  /**
   *
   * @type {number}
   * @memberof TaskSummary
   */
  state?: any;
  /**
   *
   * @type {string}
   * @memberof TaskSummary
   */
  status?: any;
  /**
   *
   * @type {Time}
   * @memberof TaskSummary
   */
  submissionTime?: any;
  /**
   *
   * @type {Time}
   * @memberof TaskSummary
   */
  startTime?: any;
  /**
   *
   * @type {Time}
   * @memberof TaskSummary
   */
  endTime?: any;
  /**
   *
   * @type {string}
   * @memberof TaskSummary
   */
  robotName?: any;
}
