/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface TaskProfile
 */
export interface TaskProfile {
  /**
   *
   * @type {string}
   * @memberof TaskProfile
   */
  task_id?: any;
  /**
   *
   * @type {Time}
   * @memberof TaskProfile
   */
  submission_time?: any;
  /**
   *
   * @type {TaskDescription}
   * @memberof TaskProfile
   */
  description?: any;
}
