/* tslint:disable */
/* eslint-disable */
/**
 * RMF API Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface TaskSummary
 */
export interface TaskSummary {
  /**
   *
   * @type {string}
   * @memberof TaskSummary
   */
  fleet_name?: any;
  /**
   *
   * @type {string}
   * @memberof TaskSummary
   */
  task_id?: any;
  /**
   *
   * @type {TaskProfile}
   * @memberof TaskSummary
   */
  task_profile?: any;
  /**
   *
   * @type {number}
   * @memberof TaskSummary
   */
  state?: any;
  /**
   *
   * @type {string}
   * @memberof TaskSummary
   */
  status?: any;
  /**
   *
   * @type {Time}
   * @memberof TaskSummary
   */
  submission_time?: any;
  /**
   *
   * @type {Time}
   * @memberof TaskSummary
   */
  start_time?: any;
  /**
   *
   * @type {Time}
   * @memberof TaskSummary
   */
  end_time?: any;
  /**
   *
   * @type {string}
   * @memberof TaskSummary
   */
  robot_name?: any;
  /**
   *
   * @type {string}
   * @memberof TaskSummary
   */
  authz_grp?: any;
}
