#!/bin/bash

# dockert = short for docker-trampoline.

# simple script that runs a command with "pkexec" if user is not in "docker" group.
# this is needed because we don't have a tty for sudo to work. "pkexec" runs a command as root and
# prompts for the password in a gui.
if groups | grep -q '\bdocker\b' || [[ $(id -u) == 0 ]]; then
  exec "$@"
else
  # execute command as root, we can't use sudo as we don't get an interactive tty. "pkexec" is the
  # gui alternative that prompts for a password in a popup.
  exec pkexec "$@"
fi
