/* tslint:disable */
/* eslint-disable */
/**
 * RMF API Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { ChargerRequest } from '../models';
import { HTTPValidationError } from '../models';
/**
 * ChargersApi - axios parameter creator
 * @export
 */
export const ChargersApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * **Available in socket.io**
     * @summary Get Charger Request
     * @param {string} charger_name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getChargerRequestChargersChargerNameRequestGet: async (
      charger_name: string,
      options: any = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'charger_name' is not null or undefined
      if (charger_name === null || charger_name === undefined) {
        throw new RequiredError(
          'charger_name',
          'Required parameter charger_name was null or undefined when calling getChargerRequestChargersChargerNameRequestGet.',
        );
      }
      const localVarPath = `/chargers/{charger_name}/request`.replace(
        `{${'charger_name'}}`,
        encodeURIComponent(String(charger_name)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, 'https://example.com');
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }
      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      const query = new URLSearchParams(localVarUrlObj.search);
      for (const key in localVarQueryParameter) {
        query.set(key, localVarQueryParameter[key]);
      }
      for (const key in options.query) {
        query.set(key, options.query[key]);
      }
      localVarUrlObj.search = new URLSearchParams(query).toString();
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * ChargersApi - functional programming interface
 * @export
 */
export const ChargersApiFp = function (configuration?: Configuration) {
  return {
    /**
     * **Available in socket.io**
     * @summary Get Charger Request
     * @param {string} charger_name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getChargerRequestChargersChargerNameRequestGet(
      charger_name: string,
      options?: any,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ChargerRequest>> {
      const localVarAxiosArgs = await ChargersApiAxiosParamCreator(
        configuration,
      ).getChargerRequestChargersChargerNameRequestGet(charger_name, options);
      return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
        const axiosRequestArgs = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        };
        return axios.request(axiosRequestArgs);
      };
    },
  };
};

/**
 * ChargersApi - factory interface
 * @export
 */
export const ChargersApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  return {
    /**
     * **Available in socket.io**
     * @summary Get Charger Request
     * @param {string} charger_name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getChargerRequestChargersChargerNameRequestGet(
      charger_name: string,
      options?: any,
    ): AxiosPromise<ChargerRequest> {
      return ChargersApiFp(configuration)
        .getChargerRequestChargersChargerNameRequestGet(charger_name, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * ChargersApi - object-oriented interface
 * @export
 * @class ChargersApi
 * @extends {BaseAPI}
 */
export class ChargersApi extends BaseAPI {
  /**
   * **Available in socket.io**
   * @summary Get Charger Request
   * @param {string} charger_name
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ChargersApi
   */
  public getChargerRequestChargersChargerNameRequestGet(charger_name: string, options?: any) {
    return ChargersApiFp(this.configuration)
      .getChargerRequestChargersChargerNameRequestGet(charger_name, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
