/* tslint:disable */
/* eslint-disable */
/**
 * RMF API Server
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { HTTPValidationError } from '../models';
import { ModelObject } from '../models';
/**
 * FireAlarmApi - axios parameter creator
 * @export
 */
export const FireAlarmApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     *
     * @summary Post Fire Alarm Request
     * @param {boolean} alarm
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    postFireAlarmRequestFireAlarmRequestPost: async (
      alarm: boolean,
      options: any = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'alarm' is not null or undefined
      if (alarm === null || alarm === undefined) {
        throw new RequiredError(
          'alarm',
          'Required parameter alarm was null or undefined when calling postFireAlarmRequestFireAlarmRequestPost.',
        );
      }
      const localVarPath = `/fire_alarm/request`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, 'https://example.com');
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }
      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (alarm !== undefined) {
        localVarQueryParameter['alarm'] = alarm;
      }

      const query = new URLSearchParams(localVarUrlObj.search);
      for (const key in localVarQueryParameter) {
        query.set(key, localVarQueryParameter[key]);
      }
      for (const key in options.query) {
        query.set(key, options.query[key]);
      }
      localVarUrlObj.search = new URLSearchParams(query).toString();
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * FireAlarmApi - functional programming interface
 * @export
 */
export const FireAlarmApiFp = function (configuration?: Configuration) {
  return {
    /**
     *
     * @summary Post Fire Alarm Request
     * @param {boolean} alarm
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async postFireAlarmRequestFireAlarmRequestPost(
      alarm: boolean,
      options?: any,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ModelObject>> {
      const localVarAxiosArgs = await FireAlarmApiAxiosParamCreator(
        configuration,
      ).postFireAlarmRequestFireAlarmRequestPost(alarm, options);
      return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
        const axiosRequestArgs = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        };
        return axios.request(axiosRequestArgs);
      };
    },
  };
};

/**
 * FireAlarmApi - factory interface
 * @export
 */
export const FireAlarmApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  return {
    /**
     *
     * @summary Post Fire Alarm Request
     * @param {boolean} alarm
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    postFireAlarmRequestFireAlarmRequestPost(
      alarm: boolean,
      options?: any,
    ): AxiosPromise<ModelObject> {
      return FireAlarmApiFp(configuration)
        .postFireAlarmRequestFireAlarmRequestPost(alarm, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * FireAlarmApi - object-oriented interface
 * @export
 * @class FireAlarmApi
 * @extends {BaseAPI}
 */
export class FireAlarmApi extends BaseAPI {
  /**
   *
   * @summary Post Fire Alarm Request
   * @param {boolean} alarm
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof FireAlarmApi
   */
  public postFireAlarmRequestFireAlarmRequestPost(alarm: boolean, options?: any) {
    return FireAlarmApiFp(this.configuration)
      .postFireAlarmRequestFireAlarmRequestPost(alarm, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
