name: PostgreSQL service example
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: 
      image: docker.pkg.github.com/open-rmf/rmf-web/e2e
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2

      # Performs a clean installation of all dependencies in the `package.json` file
      # For more information, see https://docs.npmjs.com/cli/ci.html
      - name: Install dependencies
        run: apt-get update && apt-get install -y curl python3-pip pipenv 
      - name: Install python dependencies
        run: pip3 install fastapi uvicorn tortoise-orm pydantic aerich asyncpg 
      - name: Copy migrations 
        run: cp -r packages/reporting-server/migrations/ packages/reporting-server/test_migration/migrations/

      - name: Connect to PostgreSQL and run migrations
        # Runs a script that creates a PostgreSQL table, populates
        # the table with data, and then retrieves the data.
        run: aerich upgrade
        # Environment variables used by the `client.js` script to create a new PostgreSQL table.
        env:
          # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: postgres
          POSTGRES_PASSWORD: postgres 
          # The default PostgreSQL port
          POSTGRES_PORT: 5432
          POSTGRES_DB: reporting

# name: reporting-server-migrations
# on:
#   pull_request:
#   push:
#     # branches:
#     #   - main
#   # schedule:
#   #   # 2am SGT
#   #   - cron: '0 18 * * *'
# env:
#   CI: true
# jobs:
  
#   e2e-tests:
#     name: Reporting server migration Tests
#     runs-on: ubuntu-latest
#     if: always()
#     needs: build-docker-images
#     container:
#       image: docker.pkg.github.com/open-rmf/rmf-web/reporting-server-migrations
#       credentials:
#         username: ${{ github.repository_owner }}
#         password: ${{ secrets.GITHUB_TOKEN }}
#       options: --privileged --ipc=host
#     defaults: 
#       run:
#         shell: bash
#         working-directory: packages/reporting-server
#     steps:
#       - uses: actions/checkout@v2
#       - name: bootstrap
#         run: |
#           . /opt/rmf/setup.bash
#           npm config set unsafe-perm
#           npm install -g lerna@4
#           lerna bootstrap --scope=reporting-sever
#           pip install aerich asyncpg 
#         working-directory: .
#       - name: e2e test
#         run: |
#           . /opt/rmf/setup.bash
#           aerich upgrade
#         env:
#           E2E_DOCKER_NETWORK: ${{job.container.network}}

