name: rmf-auth
on:
  pull_request:
    paths:
      - '.github/workflows/rmf-auth.yml'
      - 'packages/rmf-auth/**'
  push:
    branches:
      - main
env:
  CI: true
jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
        working-directory: packages/rmf-auth
    steps:
      - uses: actions/checkout@v2
      - name: bootstrap
        uses: ./.github/actions/bootstrap
        with:
          package: rmf-auth
      - name: lint
        run: pnpm run lint
      - name: unit test
        run: pnpm run test:coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          flags: rmf-auth
