name: rmf-auth
on:
  pull_request:
    paths:
      - '.github/workflows/rmf-auth.yml'
      - 'packages/rmf-auth/**'
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  CI: true
jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/${{ github.repository }}/minimal-rmf
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        shell: bash
        working-directory: packages/rmf-auth
    steps:
      - uses: actions/checkout@v4
      - name: bootstrap
        uses: ./.github/actions/bootstrap
        with:
          package: rmf-auth
      - name: lint
        run: pnpm run lint
      - name: unit test
        run: pnpm run test:coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          flags: rmf-auth
