 
name: rmf-models
on:
  pull_request:
    paths:
      - 'packages/rmf-models/**'
  push:
    branches:
      - main
env:
  CI: true
jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/open-rmf/rmf-web/e2e
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        shell: bash
        working-directory: packages/rmf-models
    steps:
      - uses: actions/checkout@v2
      - name: bootstrap
        run: |
          . /opt/rmf/setup.bash
          npm config set unsafe-perm
          npm run bootstrap -- packages/rmf-models
        working-directory: .
      - name: test
        run: . /opt/rmf/setup.bash && npm test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: rmf-models
