/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Clean a zone
 */
export interface CleanEvent {
  zone: string;
  type?: string;
  [k: string]: unknown;
}
