/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Description of a place that the robot can go to
 */
export type PlaceDescription =
  | (string | number)
  | {
      waypoint: string | number;
      orientation?: number;
      [k: string]: unknown;
    };

/**
 * Description for a drop off or a pick up event category
 */
export interface DropOffEventDescription {
  place: PlaceDescription;
  handler?: string;
  payload: PayloadComponent | PayloadComponent[];
  [k: string]: unknown;
}
export interface PayloadComponent {
  sku: string;
  quantity: number;
  compartment?: string;
  [k: string]: unknown;
}
