/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Have a robot go to a place
 */
export type GoToPlaceEventDescription =
  | PlaceDescription
  | {
      place: PlaceDescription;
      /**
       * A list of places that the robot might go after it reaches this one. It will not actually go to these places unless other activities bring it there, but the traffic system will be told to expect the robot to proceed through these places.
       */
      followed_by?: PlaceDescription[];
      [k: string]: unknown;
    };
/**
 * Description of a place that the robot can go to
 */
export type PlaceDescription =
  | (string | number)
  | {
      waypoint: string | number;
      orientation?: number;
      [k: string]: unknown;
    };
