/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Description of a place that the robot can go to
 */
export type PlaceDescription =
  | (string | number)
  | {
      waypoint: string | number;
      orientation?: number;
      [k: string]: unknown;
    };

/**
 * Description of a patrolling task
 */
export interface PatrolTaskDescription {
  /**
   * A list of which places to patrol between
   */
  places: PlaceDescription[];
  /**
   * How many times the patrol should be performed. By default this is 1.
   */
  rounds?: number;
  [k: string]: unknown;
}
