/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Compose a task description based on activities that are supported by fleets. When supported by fleets, this can be used as a task description for task_request.
 */
export interface ComposeTaskDescription {
  /**
   * Specify the category for this composed task, as the operators should see it.
   */
  category?: string;
  /**
   * Specify the detail for this composed task, as the operators should see it.
   */
  detail?: string;
  /**
   * List the phases of the task in the order that they should be performed.
   */
  phases: {
    activity: Activity;
    /**
     * A list of activities to perform if the task is canceled during this phase. Each activity is given its own phase which can be skipped but not canceled.
     */
    on_cancel?: Activity[];
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
/**
 * Describe the activity of the phase. This must match an activity description supported by one of the fleets. If there should be multiple activities within a phase, then use a Sequence activity.
 */
export interface Activity {
  /**
   * The category of this phase's activity.
   */
  category: string;
  /**
   * A description of the activity. This must match a schema supported by a fleet for the category of this activity.
   */
  description: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
