/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Description of a place that the robot can go to
 */
export type PlaceDescription =
  | (string | number)
  | {
      waypoint: string | number;
      orientation?: number;
      [k: string]: unknown;
    };

/**
 * Description for a simple delivery task category
 */
export interface DeliveryTaskDescription {
  pickup: PickUpEventDescription;
  dropoff: DropOffEventDescription;
  [k: string]: unknown;
}
/**
 * Description for a drop off or a pick up event category
 */
export interface PickUpEventDescription {
  place: PlaceDescription;
  handler?: string;
  payload:
    | {
        sku: string;
        quantity: number;
        compartment?: string;
        [k: string]: unknown;
      }
    | {
        sku: string;
        quantity: number;
        compartment?: string;
        [k: string]: unknown;
      }[];
  [k: string]: unknown;
}
/**
 * Description for a drop off or a pick up event category
 */
export interface DropOffEventDescription {
  place: PlaceDescription;
  handler?: string;
  payload:
    | {
        sku: string;
        quantity: number;
        compartment?: string;
        [k: string]: unknown;
      }
    | {
        sku: string;
        quantity: number;
        compartment?: string;
        [k: string]: unknown;
      }[];
  [k: string]: unknown;
}
